### ISSUE TITLE
Brightness Control

### ISSUE THREAD

**Issue by schmidtwmark** [SchmidtScoreboard/rust-scoreboard#6]
Brightness is tweakable, it should be stored in scoreboard_settings.json and updateable from the app. It may require a restart of the scoreboard or at least the binary, but I could probably make it work with a MatrixCommand

**Comment by rgw3d** [comment]
IMO this should be the next issue you fix. If the TV isn't on, the scoreboard is very bright. So bright that I need to turn it off (which is very easy to do, but still).

I'd love to see a simple brightness adjustment, and maybe a way to auto-dim based on the time?

**Comment by schmidtwmark** [comment]
That's a good point, it is relatively low hanging fruit. The only trouble is that it will require an app update, which I hate doing. But I've got another app update planned, so it'll be okay.
